name: Ensure lists are sorted

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Ensure Sorted Order
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.10'

      - name: Sort file content order
        run: |
          python ./scripts/sorter.py

      - name: Commit & Push Results, if needed
        id: push_results
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No files changed, nothing to do"
            exit 0
          fi

          git config user.name 'Sorted Order Validation'
          git config user.email 'hello@sublimesecurity.com'
          git add '*.txt'
          git commit -m "Auto sorting static files"

          git push origin HEAD:${HEAD_REF}
