name: Validate manifest.json

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate manifest.json
        id: validate_manifest
        run: |
          echo "Validating manifest files"
          for item in $(jq -c -r '.lists.[].file | select( . != null )' manifest.json); do
            if test -f $item; then
              echo "$item exists"
            else
              echo "::error file=manifest.json,title=Invalid-Manifest::$item does not exist"
              exit 1
            fi
          done

          echo "Validating manifest urls"
          for item in $(jq -c -r '.lists.[].url | select( . != null )' manifest.json); do
            urlstatus=$(curl -H 'Cache-Control: no-cache' -o /dev/null --silent --head --write-out "$URL %{http_code}" "$item")
            if [ $urlstatus -ne 200 ]; then
              echo "::error file=manifest.json,title=Invalid-Manifest::$item has HTTP status of $urlstatus"
              exit 1
            fi
          done

          echo "Validation complete"
